import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { InterviewQuestion } from './interview-question.entity';
import { LeadRepository } from '../leads/lead.repository';

/**
 * Seed bank of interview questions per topic. Practice sets are generated by
 * matching a job lead's required skills to these topics.
 */
const SEED: Array<Pick<InterviewQuestion, 'topic' | 'question' | 'answerGuide' | 'difficulty'>> = [
	// NestJS
	{ topic: 'nestjs', question: 'Explain the NestJS request lifecycle (middleware → guards → interceptors → pipes → filters).', answerGuide: 'Order matters: middleware runs first, then guards (auth), interceptors (wrap handler), pipes (validation/transformation), handler, then exception filters on errors.', difficulty: 3 },
	{ topic: 'nestjs', question: 'How do dependency injection and the IoC container work in NestJS?', answerGuide: 'Classes decorated @Injectable are provided in modules; the container instantiates and caches singletons by token; constructor injection resolves the graph.', difficulty: 2 },
	{ topic: 'nestjs', question: 'Difference between providers, controllers and modules. When would you use a custom provider?', answerGuide: 'Controllers handle HTTP; providers hold logic/data; modules organize them. Custom providers (useFactory/useValue) for config-driven or third-party clients.', difficulty: 3 },
	{ topic: 'nestjs', question: 'How would you implement rate limiting and Helmet security in a NestJS API?', answerGuide: 'ThrottlerModule for rate limit, helmet middleware, ValidationPipe with whitelist, CORS restricted origins.', difficulty: 2 },
	// TypeScript
	{ topic: 'typescript', question: 'Explain generics with a practical example from an API service.', answerGuide: 'e.g. Repository<T> or ApiResponse<T> — reusable typed structures; constraints via extends.', difficulty: 2 },
	{ topic: 'typescript', question: 'What are discriminated unions and how do they make state handling safer?', answerGuide: 'A shared literal field narrows the union in switch/if checks, e.g. {status:"ok",data}|{status:"error",message}.', difficulty: 3 },
	{ topic: 'typescript', question: 'unknown vs any vs never — when to use each?', answerGuide: 'unknown for safe inputs needing narrowing, never for unreachable code/exhaustiveness, avoid any.', difficulty: 3 },
	// MySQL / backend
	{ topic: 'mysql', question: 'How do you find and fix a slow query?', answerGuide: 'EXPLAIN the plan, check index usage, avoid SELECT *, add covering indexes, consider query rewrite or caching.', difficulty: 3 },
	{ topic: 'mysql', question: 'Explain transaction isolation levels and common anomalies.', answerGuide: 'READ UNCOMMITTED→SERIALIZABLE; dirty read, non-repeatable read, phantom read; MySQL default REPEATABLE READ.', difficulty: 4 },
	{ topic: 'mysql', question: 'Connection pooling — why is it essential in a Node.js + MySQL app?', answerGuide: 'Reuses TCP+auth handshakes across requests, caps concurrent connections, prevents exhaustion under load.', difficulty: 2 },
	{ topic: 'system-design', question: 'Design a job-application tracking service: tables, APIs, and how you would scale it.', answerGuide: 'users/applications/jobs tables, REST endpoints, queue for async submissions, DB indexes on (user_id,status), cache hot reads.', difficulty: 4 },
	{ topic: 'system-design', question: 'How would you design scheduled background jobs (like daily scraping) reliably?', answerGuide: 'Cron with leader election or BullMQ queues, idempotent handlers, retry with backoff, dead-letter logging.', difficulty: 4 },
	// HR / behavioral
	{ topic: 'hr', question: 'Why are you looking for a remote role now?', answerGuide: 'Frame positively: seeking global impact and ownership; mention leading teams remotely at Han River successfully.', difficulty: 1 },
	{ topic: 'hr', question: 'Tell me about a time you led a team through a difficult delivery.', answerGuide: 'Use STAR: situation at Han River, task deadline risk, action = re-prioritization + task breakdown, result = on-time release.', difficulty: 2 },
	{ topic: 'hr', question: 'What are your salary expectations?', answerGuide: 'Give researched range aligned to profile.salaryExpectation; ask for their band first if possible.', difficulty: 1 },
];

@Injectable()
export class InterviewPrepService implements OnModuleInit {
	private readonly logger = new Logger(InterviewPrepService.name);

	constructor(
		@InjectRepository(InterviewQuestion) private readonly repo: Repository<InterviewQuestion>,
		private readonly leadRepo: LeadRepository,
	) {}

	async onModuleInit(): Promise<void> {
		const count = await this.repo.count();
		if (count === 0) {
			await this.repo.save(this.repo.create(SEED));
			this.logger.log(`seeded ${SEED.length} interview questions`);
		}
	}

	listAll(): Promise<InterviewQuestion[]> {
		return this.repo.find({ order: { topic: 'ASC', difficulty: 'ASC' } });
	}

	/** Practice set tailored to one job lead: questions from the skills that lead mentions. */
	async practiceForLead(leadId: string): Promise<{ lead: string; topics: string[]; questions: InterviewQuestion[] }> {
		const lead = (await this.leadRepo.findRecent(500)).find((l) => l.id === leadId);
		if (!lead) throw new Error('lead not found');
		const text = `${lead.title} ${lead.description ?? ''}`.toLowerCase();
		const topicMap: Record<string, string[]> = {
			nestjs: ['nest', 'node'],
			typescript: ['typescript', 'ts'],
			mysql: ['sql', 'mysql', 'database'],
			'system-design': ['architect', 'scale', 'senior', 'lead'],
			hr: [],
		};
		const topics = Object.entries(topicMap)
			.filter(([, kws]) => kws.some((k) => text.includes(k)))
			.map(([t]) => t);
		if (topics.length === 0) topics.push('nestjs', 'typescript');
		topics.push('hr'); // always include behavioral
		const questions = await this.repo
			.createQueryBuilder('q')
			.where('q.topic IN (:...topics)', { topics })
			.orderBy('q.difficulty', 'ASC')
			.getMany();
		return { lead: `${lead.title} @ ${lead.company}`, topics, questions };
	}
}
