import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

/**
 * A PRE-CLEARED desk instruction: the operator states a contract, a side and a
 * capital cap ONCE, and the desk opens it by itself at the next session open.
 *
 * Why this exists: re-issuing the same instruction every trading day was costing
 * the first hours of the session. This row is that instruction, persisted.
 *
 * Safety properties (deliberate):
 *  - It carries NO strategy of its own: the operator names the contract. Nothing
 *    is inferred, no level and no expiry is generated by code.
 *  - It is inert unless `enabled` AND the portfolio's own `autoTradeEnabled` is
 *    on AND the row is due for the session (see upstox-live-paper-instruction.rules).
 *  - One execution per instruction per session, enforced by `lastExecutedSession`.
 *  - Isolation: own table, dataSource=UPSTOX, executionMode=PAPER.
 */
@Entity('upstox_live_paper_instructions')
@Index('idx_ulpi_due', ['enabled', 'sessionDate'])
@Index('idx_ulpi_portfolio', ['portfolioId'])
export class UpstoxLivePaperInstruction {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** Human label, e.g. 'sensex PE reversal — pre-cleared'. */
  @Column({ length: 128, default: 'pre-cleared instruction' })
  label: string;

  /** Paper portfolio to trade in. Null → the first portfolio is used. */
  @Column({ name: 'portfolioId', type: 'varchar', length: 36, nullable: true })
  portfolioId: string | null;

  /** Exact contract to trade, e.g. SENSEX26102286000PE. Must end in CE/PE. */
  @Column({ length: 64 })
  instrument: string;

  /** Underlying short name (SENSEX / NIFTY). Checked against the desk's universes. */
  @Column({ type: 'varchar', length: 32, nullable: true })
  underlying: string | null;

  @Column({ type: 'varchar', length: 2, nullable: true })
  optionType: 'CE' | 'PE' | null;

  @Column({ type: 'date', nullable: true })
  expiry: string | null;

  @Column({ type: 'decimal', precision: 14, scale: 4, nullable: true })
  strike: number | null;

  @Column({ length: 4, default: 'BUY' })
  side: 'BUY' | 'SELL';

  /**
   * Lots to open. Null → derived from `maxCapital` at the observed premium
   * (never a hard-coded quantity).
   */
  @Column({ type: 'int', nullable: true })
  lots: number | null;

  /**
   * Contract lot size. Null → resolved from UPSTOX_LIVE_PAPER_LOT_SIZE, then the
   * broker's own contract master. Never guessed: unresolved skips the order.
   */
  @Column({ type: 'int', nullable: true })
  lotSize: number | null;

  /** Per-position capital cap (INR). Required: no cap → no order. */
  @Column({ type: 'decimal', precision: 14, scale: 2, nullable: true })
  maxCapital: number | null;

  /** 'YYYY-MM-DD' for a one-shot instruction; null = every trading session. */
  @Column({ type: 'date', nullable: true })
  sessionDate: string | null;

  @Column({ default: true })
  enabled: boolean;

  @Column({ type: 'varchar', length: 255, nullable: true })
  notes: string | null;

  /** Times this instruction has fired. */
  @Column({ type: 'int', default: 0 })
  executions: number;

  /** IST session date ('YYYY-MM-DD') of the last execution — the once-per-session guard. */
  @Column({ type: 'varchar', length: 10, nullable: true })
  lastExecutedSession: string | null;

  @Column({ type: 'datetime', nullable: true })
  lastExecutedAt: Date | null;

  /** Last outcome: executed / skipped reason / trade id. */
  @Column({ type: 'json', nullable: true })
  lastResult: Record<string, unknown> | null;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
