#!/usr/bin/env node
'use strict';
const load=(f)=>require('../dist/job-application/'+f);
const S=load('precision-application-queue.service.js');
const svc=new S.PrecisionApplicationQueueService();
let P=0,F=0;const eq=(l,g,w)=>{const o=JSON.stringify(g)===JSON.stringify(w);process.stdout.write((o?'✔':'✘')+' '+l+': got '+JSON.stringify(g)+' want '+JSON.stringify(w)+'\n');return o;};
const T=(l,fn)=>{try{if(fn())P++;else F++;}catch(e){F++;console.log('✘ '+l+': '+e.message);}};
svc.enqueue({applicationId:'app-1',opportunityScore:80,target:'high_paying',queuedAt:'2026-01-01T00:00:00Z'});
svc.enqueue({applicationId:'app-2',opportunityScore:30,target:'high_paying',queuedAt:'2026-01-01T00:00:00Z'});
svc.enqueue({applicationId:'app-3',opportunityScore:50,target:'balanced',queuedAt:'2026-01-01T00:00:00Z'});
svc.enqueue({applicationId:'app-4',opportunityScore:90,target:'balanced',queuedAt:'2026-01-01T00:00:00Z'});
const q1Id=svc.getByPriority('high')[0].id;
const lowQ=svc.getByPriority('low');
svc.enqueue({applicationId:'app-5',opportunityScore:95,target:'balanced',queuedAt:'2026-01-01T00:00:00Z'});
const q2Id=svc.getByPriority('high')[0].id;
T('enqueue',()=>eq('id',!!q1Id,true));
T('count',()=>eq('cnt',svc.getCount(),5));
T('getById',()=>eq('found',!!svc.getById(q1Id),true));
T('getQueue',()=>{const q=svc.getQueue();return eq('len',q.length,5);});
T('getByPriority high',()=>{const h=svc.getByPriority('high');return eq('len',h.length,2);});
T('getByPriority low',()=>{return eq('len',lowQ.length,1);});
T('getByTarget',()=>{const t=svc.getByTarget('high_paying');return eq('len',t.length,2);});
T('updateScore',()=>{const q=svc.updateScore(q1Id,95);return eq('score',q.opportunityScore,95);});
T('reorder',()=>{svc.reorder();const q=svc.getQueue();return eq('first',q[0].id,q2Id);});
T('dequeue',()=>{svc.dequeue(q2Id);return eq('cnt',svc.getCount(),4);});
T('summary',()=>{const s=svc.getSummary();return eq('total',s.total,4);});
T('inferPriority',()=>{return eq('high',svc.inferPriority(80),'high');});
T('calculateScore',()=>{const s=svc.calculateScore({opportunityScore:50,appliedAt:'2026-01-05T00:00:00Z'});return typeof s==='number';});
console.log('\nResults: '+(P===14?'passed':'failed')+','+P+' passed,'+F+' failed,14 expected\n');process.exit(P===14?0:1);
