#!/usr/bin/env node
'use strict';
const load=(f)=>require('../dist/job-application/'+f);
const S=load('learning-safety-guardrails.service.js');
const svc=new S.LearningSafetyGuardrailsService();
let P=0,F=0;const eq=(l,g,w)=>{const o=JSON.stringify(g)===JSON.stringify(w);process.stdout.write((o?'✔':'✘')+' '+l+': got '+JSON.stringify(g)+' want '+JSON.stringify(w)+'\n');return o;};
const T=(l,fn)=>{try{if(fn())P++;else F++;}catch(e){F++;console.log('✘ '+l+': '+e.message);}};
const c1=svc.addConfig({type:'rate_limit',name:'max_per_day',threshold:100,action:'warn'});
const c2=svc.addConfig({type:'max_value',name:'max_score',threshold:100,action:'block'});
svc.disable(c2.id);
svc.check(c1.id,50);
svc.check(c1.id,150);
svc.check(c2.id,150);
svc.enable(c2.id);
svc.recordViolation(c1.id,'critical','test violation',{test:true});
svc.recordViolation(c2.id,'warning','another violation',{test:true});
T('addConfig',()=>eq('name',c1.name,'max_per_day'));
T('getConfig',()=>eq('found',!!svc.getConfig(c1.id),true));
T('getConfigs',()=>eq('len',svc.getConfigs().length,2));
T('enable/disable',()=>{svc.disable(c1.id);const e=svc.enable(c1.id);return eq('enabled',e.enabled,true);});
T('check pass',()=>{svc.enable(c2.id);const r=svc.check(c1.id,50);return eq('status',r.status,'pass');});
T('check warn',()=>{const r=svc.check(c1.id,150);return eq('status',r.status,'warn');});
T('check block',()=>{svc.enable(c2.id);const r=svc.check(c2.id,150);return eq('status',r.status,'block');});
T('check unknown',()=>{const r=svc.check('unknown-id',100);return eq('status',r.status,'pass');});
T('recordViolation',()=>{svc.recordViolation(c1.id,'critical','v1',{});svc.recordViolation(c2.id,'warning','v2',{});return eq('v.cnt',svc.getViolationCount(),2);});
T('getViolation',()=>{const v=svc.getViolations();return eq('v1_sev',v[0].severity,'critical');});
T('getViolations',()=>eq('v.len',svc.getViolations().length,2));
T('evaluateAll',()=>{svc.enable(c2.id);const r=svc.evaluateAll(50);return eq('eval len',r.length,2);});
T('getState',()=>{svc.enable(c1.id);svc.enable(c2.id);const s=svc.getState();return eq('total',s.totalChecks,2);});
T('getCount',()=>eq('cnt',svc.getCount(),2));
console.log('\nResults: '+(P===15?'passed':'failed')+','+P+' passed,'+F+' failed,15 expected\n');process.exit(P===15?0:1);
