#!/usr/bin/env node
'use strict';
const load=(f)=>require('../dist/job-application/'+f);
const S=load('kpi-dashboard.service.js');
const svc=new S.KPIDashboardService();
let P=0,F=0;const eq=(l,g,w)=>{const o=JSON.stringify(g)===JSON.stringify(w);process.stdout.write((o?'✔':'✘')+' '+l+': got '+JSON.stringify(g)+' want '+JSON.stringify(w)+'\n');return o;};
const T=(l,fn)=>{try{if(fn())P++;else F++;}catch(e){F++;console.log('✘ '+l+': '+e.message);}};
svc.record('applications_tracked',10,'daily','2026-01-01T00:00:00Z');
svc.record('applications_tracked',15,'daily','2026-01-02T00:00:00Z');
svc.record('applications_tracked',20,'daily','2026-01-03T00:00:00Z');
svc.record('interview_rate',0.3,'daily','2026-01-01T00:00:00Z');
svc.record('interview_rate',0.4,'daily','2026-01-02T00:00:00Z');
svc.record('offer_rate',0.1,'daily','2026-01-01T00:00:00Z');
svc.record('offer_rate',0.15,'daily','2026-01-02T00:00:00Z');
svc.record('acceptance_rate',0.5,'daily','2026-01-01T00:00:00Z');
svc.record('acceptance_rate',0.6,'daily','2026-01-02T00:00:00Z');
svc.record('response_rate',0.8,'daily','2026-01-01T00:00:00Z');
svc.record('response_rate',0.85,'daily','2026-01-02T00:00:00Z');
T('record count',()=>eq('cnt',svc.getCount(),5));
const c=svc.compute('applications_tracked','daily');
T('compute',()=>eq('val',c.value,20));
const k=svc.getKPI('applications_tracked','daily');
T('getKPI',()=>eq('val',k.value,20));
T('getKPI trend',()=>eq('trend',k.trend,'up'));
const d=svc.getDashboard('daily');
T('getDashboard',()=>eq('len',d.kpis.length,10));
T('getSnapshot missing',()=>eq('missing',svc.getSnapshot('nonexistent-id-12345'),undefined));
const sn=svc.getRecentSnapshots(5);
T('getRecentSnapshots',()=>eq('len',sn.length,1));
const t=svc.getTrend('applications_tracked','daily');
T('getTrend',()=>eq('trend',t,'up'));
const ss=svc.getSummaryStats();
T('getSummaryStats',()=>eq('total',ss.totalKPIs,10));
T('getSnapshotCount',()=>eq('sc',svc.getSnapshotCount(),1));
T('getTrend insufficient',()=>{const t=svc.getTrend('rejection_rate','daily');return eq('trend',t,'insufficient_data');});
T('compute previous',()=>eq('prev',c.previousValue,15));
console.log('\nResults: '+(P===12?'passed':'failed')+','+P+' passed,'+F+' failed,12 expected\n');process.exit(P===12?0:1);
